language: go
go: 
 - 1.9

env:
  global:
    - GOARCH=amd64
    - GOOS=windows
    - CGO_ENABLED=0

script:
 - go build -v ./...
 
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  bucket: ktl.s3.apps
  upload-dir: Test
  skip_cleanup: true
