language: go
go: 
 - 1.9
 
script:
 - go build -v ./...
 
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: ktl.s3.apps
  skip_cleanup: true
