language: go
go: 
 - 1.9

env:
  global:
    - GOARCH=amd64
    - GOOS=windows
    - CGO_ENABLED=0

script:
 - GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -v ./...
 - GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -v ./...
 
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  bucket: ktl.apps
  upload-dir: Test
  skip_cleanup: true
